language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Z3vfHLwGeL8r9u4p/4EFZm2bk55Xsu5vOmTNA9n5qYsZnL/3pnepfcc060zzfZjl6xLR+ff6TbreqAchWRR/u/BjBMQnmBiuj5eylA9CSRcS2UCFmZyBxOY8UAf7R+Wagu/DHwmI1wgNFH3S3AoKAZDgwISHIrOLRB20eE6nX30GFk/x2c/i3d5NLRI0B3pzUH4ttRWwYpEhObwkBSlVtmU9rEIkMqbnq9DA6v1cMdAzW5kYLk97YbQ62hAUI/eGAmkLDTjCetaKcTek2c1xp3Syse9Pr52CDo097oA4xI68e13MngUUVO1oZb+etBwfYEPxeksMD6HmbKA5RQep7WY3MQ7Ybbt/UhvAdQDAfqyoW5ax1/4UwoqpKYtXlkDy/FCSEHmteciZm4/4YxuZwnujB0eBaxc7e3oF9dQykLvEWK3pEHC0kEB3KZxSZSWdXiEfacdIpBxlWTs0Ih6EfXKx61jPrIPjfQEaIyNBf5bP1gOOpODr+xkWr3hmBoT6am6RkzhjMzfJC6OB8/rD1eS/E/eHojgy2ifv4DH5A5RHxtLBoYRhCXLVIAGq+vVaPynDVmtrFHaEK9WfXQsc/x09OInXS8THGqe4xn/3/sVQlGoeh/O0eZUQlb1ZrD5gT7zlm5/2q1QawCd0ufeQOZ+VyLWFMIqb0ixkebibDvg=
  file:
    - "retext-indefinite-article.js"
    - "retext-indefinite-article.min.js"
  on:
    tags: true
    node: '9.0'
